spring:
 cloud:
   gateway:
     globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PATCH
            - DELETE
            - PUT
     routes:
       - id: user-service
         uri: http://localhost:8082
         predicates:
           - Path=/user/**
         filters:
           - AuthenticationFilter
           
       - id: authentication_service
         uri: http://localhost:8081
         predicates:
           - Path=/auth/**
         filters:
           - AuthenticationFilter
           
       - id: order_service
         uri: http://localhost:8083
         predicates:
            - Path=/orders/**
         filters:
            - AuthenticationFilter
            
       - id: bulknotification_service
         uri: http://localhost:8085
         predicates:
            - Path=/bulknotification/**
         filters:
            - AuthenticationFilter
       - id: email_service
         uri: http://localhost:8084
         predicates:
            - Path=/email/**
         filters:
            - AuthenticationFilter
        